plugins {
    id "com.android.library"
    id "org.jetbrains.kotlin.multiplatform"
    id "org.jetbrains.kotlin.plugin.serialization"
    id "maven-publish"
    id "app.cash.sqldelight" version "2.3.2"
}

group = "org.bibletranslationtools"
version = "1.0.3"

kotlin {
    jvmToolchain(11)

    androidTarget {
        publishLibraryVariants("release")
    }
    jvm()

    sourceSets {
        commonMain {
            dependencies {
                implementation "org.bibletranslationtools:resource-container:1.0.2"
                implementation "org.bibletranslationtools:logger:3.0.1"

                implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.11.0"

                // Ktor
                implementation "io.ktor:ktor-client-core:3.4.3"
                implementation "io.ktor:ktor-client-okhttp:3.4.3"
                implementation "io.ktor:ktor-client-content-negotiation:3.4.3"
                implementation "io.ktor:ktor-serialization-kotlinx-json:3.4.3"

                // SQLDelight
                implementation "app.cash.sqldelight:runtime:2.3.2"
                implementation "app.cash.sqldelight:coroutines-extensions:2.3.2"
            }
        }

        commonTest {
            dependencies {
                implementation(kotlin("test"))
                implementation("io.ktor:ktor-client-mock:3.4.3")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.10.2")
            }
        }

        androidMain {
            dependencies {
                implementation "app.cash.sqldelight:android-driver:2.3.2"
                implementation("com.github.requery:sqlite-android:3.49.0")
            }
        }

        jvmMain {
            dependencies {
                implementation "app.cash.sqldelight:sqlite-driver:2.3.2"
            }
        }
    }
}

android {
    namespace "org.bibletranslationtools.resourcecatalog"
    compileSdk = 35
    defaultConfig {
        minSdk 23
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig = true
    }
    packagingOptions {
        exclude 'lib/x86/libsqlite3x.so'
        exclude 'lib/x86_64/libsqlite3x.so'
    }
}

publishing {
    publications.withType(MavenPublication).configureEach {
        groupId = group
        version = version
        pom {
            name = "Resource Catalog Client"
            description = "A client library for interacting with the resource catalogs"
            inceptionYear = "2026"
            url = "https://github.com/bibletranslationtools/kmp-resource-catalog-client/"
            licenses {
                license {
                    name = "GNU GENERAL PUBLIC LICENSE, Version 2.0"
                    url = "http://www.gnu.org/licenses/gpl-2.0.en.html"
                    distribution = "repo"
                }
            }
            developers {
                developer {
                    id = "bibletranslationtools"
                    name = "BibleTranslationTools"
                    url = "https://github.com/bibletranslationtools/"
                }
            }
            scm {
                url = "https://github.com/bibletranslationtools/kmp-resource-catalog-client/"
                connection = "scm:git:git://github.com/bibletranslationtools/kmp-resource-catalog-client.git"
                developerConnection = "scm:git:ssh://git@github.com/bibletranslationtools/kmp-resource-catalog-client.git"
            }
            issueManagement {
                url = "https://github.com/bibletranslationtools/kmp-resource-catalog-client/issues"
                system = "github"
            }
        }
    }

    repositories {
        maven {
            name = "Nexus"
            url = version.endsWith('SNAPSHOT')
                ? "https://nexus-registry.walink.org/repository/maven-snapshots"
                : "https://nexus-registry.walink.org/repository/maven-releases"

            credentials {
                username = project.findProperty("repoUser") ?: System.getenv("REPO_USER")
                password = project.findProperty("repoPassword") ?: System.getenv("REPO_PASSWORD")
            }
        }
    }
}

sqldelight {
    databases {
        register("Database") {
            packageName = "org.bibletranslationtools.resourcecatalog"
            dialect("app.cash.sqldelight:sqlite-3-38-dialect:2.3.2")
        }
    }
}
